name: hello world
on:
  push: 
    branches: [master]
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "TODAY=$(date +%y-%m-%d)" 
      - run: echo Hello World, today is $TODAY